services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    environment:
      PB_ADMIN_EMAIL: ${PB_ADMIN_EMAIL}
      PB_ADMIN_PASSWORD: ${PB_ADMIN_PASSWORD}
    volumes:
      - pb_data:/pb_data
      - ./pb_migrations:/pb_migrations
    command: ["--migrationsDir=/pb_migrations"]
    restart: unless-stopped

volumes:
  pb_data:
