/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: "@request.auth.id != ''",
      deleteRule: "@request.auth.id = owner.id",
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          hidden: false,
          id: "file2359244304",
          maxSelect: 1,
          maxSize: 104857600,
          mimeTypes: null,
          name: "file",
          protected: false,
          required: true,
          system: false,
          thumbs: null,
          type: "file",
        },
        {
          cascadeDelete: true,
          collectionId: "_pb_users_auth_",
          hidden: false,
          id: "relation3479234172",
          maxSelect: 1,
          minSelect: 0,
          name: "owner",
          required: true,
          system: false,
          type: "relation",
        },
        {
          hidden: false,
          id: "number2117880836",
          max: null,
          min: null,
          name: "file_size",
          onlyInt: false,
          required: false,
          system: false,
          type: "number",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text3621721704",
          max: 0,
          min: 0,
          name: "file_name",
          pattern: "",
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          hidden: false,
          id: "autodate2990389176",
          name: "created",
          onCreate: true,
          onUpdate: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate3332085495",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          system: false,
          type: "autodate",
        },
      ],
      id: "pbc_3446931122",
      indexes: [],
      listRule: "@request.auth.id = owner.id",
      name: "files",
      system: false,
      type: "base",
      updateRule: null,
      viewRule: "@request.auth.id = owner.id",
    });

    return app.save(collection);
  },
  (app) => {
    const collection = app.findCollectionByNameOrId("pbc_3446931122");
    return app.delete(collection);
  }
);
